package main

import (
	"droidsh/utils"
	rl "github.com/chzyer/readline"
)

var completer = rl.NewPrefixCompleter(
	// Builtin commands
	rl.PcItem("prompt", rl.PcItemDynamic(utils.PromptGenerator)),
	rl.PcItem("clear"),
	rl.PcItem("loc"),

	// Android commands
	rl.PcItem("help", rl.PcItemDynamic(utils.AndroidCommands)),
	rl.PcItem("help-verbose"),
	rl.PcItem("ping"),
	rl.PcItem("automation",
		rl.PcItem("record"),
		rl.PcItem("stop-record"),
		rl.PcItem("play"),
		rl.PcItem("stop-play"),
	),
	rl.PcItem("event",
		rl.PcItem("send"),
		rl.PcItem("types"),
		rl.PcItem("codes"),
		rl.PcItem("text"),
		rl.PcItem("mouse"),
	),
	rl.PcItem("geo",
		rl.PcItem("nmea"),
		rl.PcItem("fix"),
		rl.PcItem("gnss"),
	),
	rl.PcItem("gsm",
		rl.PcItem("list"),
		rl.PcItem("call"),
		rl.PcItem("busy"),
		rl.PcItem("hold"),
		rl.PcItem("accept"),
		rl.PcItem("cancel"),
		rl.PcItem("data"),
		rl.PcItem("meter"),
		rl.PcItem("voice"),
		rl.PcItem("status"),
		rl.PcItem("signal"),
		rl.PcItem("signal-profile"),
	),
	rl.PcItem("cdma",
		rl.PcItem("ssource"),
		rl.PcItem("prl_version"),
	),
	rl.PcItem("crash-on-exit"),
	rl.PcItem("network",
		rl.PcItem("status"),
		rl.PcItem("speed"),
		rl.PcItem("delay"),
		rl.PcItem("capture"),
	),
	rl.PcItem("grpc"),
	rl.PcItem("power",
		rl.PcItem("display"),
		rl.PcItem("ac"),
		rl.PcItem("status"),
		rl.PcItem("present"),
		rl.PcItem("health"),
		rl.PcItem("capacity"),
	),
	rl.PcItem("redir",
		rl.PcItem("list"),
		rl.PcItem("add"),
		rl.PcItem("del"),
	),
	rl.PcItem("sms",
		rl.PcItem("send"),
		rl.PcItem("pdu"),
	),
	rl.PcItem("avd",
		rl.PcItem("name"), rl.PcItem("grpc"),
	),
	rl.PcItem("qemu",
		rl.PcItem("monitor"),
	),
	rl.PcItem("sensor",
		rl.PcItem("status"),
		rl.PcItem("get"),
		rl.PcItem("set"),
	),
	rl.PcItem("physics",
		rl.PcItem("record-gt"),
		rl.PcItem("stop"),
	),
	rl.PcItem("finger",
		rl.PcItem("touch"),
		rl.PcItem("remove"),
	),
	rl.PcItem("debug"),
	rl.PcItem("rotate"),
	rl.PcItem("screenrecord",
		rl.PcItem("start"),
		rl.PcItem("stop"),
		rl.PcItem("screenshot"),
		rl.PcItem("webrtc"),
	),
	rl.PcItem("fold"),
	rl.PcItem("unfold"),
	rl.PcItem("posture"),
	rl.PcItem("multidisplay",
		rl.PcItem("add"),
		rl.PcItem("del"),
	),
	rl.PcItem("icebox",
		rl.PcItem("track"),
	),
	rl.PcItem("nodraw"),
	rl.PcItem("resize-display",
		rl.PcItem("0"),
		rl.PcItem("1"),
		rl.PcItem("2"),
		rl.PcItem("3"),
	),
)
